// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.wait(until.elementLocated(By.name("username")), 5000)
}

describe('Login', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.sleep(2000);
    await driver.quit();
  })
  it('logs in with correct username and password', async function () {
    await navigateToLogin(driver);
    // key in correct username and password
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("seand")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123")
    await driver.findElement(By.name("rememberMeLogin")).click()
    await driver.findElement(By.id(":r2:")).click()

    // success toast should be shown
    const toast = await driver.wait(until.elementLocated(By.css(".login-success-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Login successful!');
    assert.strictEqual(await driver.getCurrentUrl(), 'http://localhost:3000/dashboard/app');
  })

  it('error toast shown when username invalid', async function () {
    await navigateToLogin(driver);
    // key in invalid username
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("sean2")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("12")
    await driver.findElement(By.name("rememberMeLogin")).click()
    await driver.findElement(By.id(":r2:")).click()

    // failure toast should be shown
    const toast = await driver.wait(until.elementLocated(By.css(".login-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Login failure!\nInvalid username or password');
  })

  it('error toast shown when password is incorrect', async function () {
    await navigateToLogin(driver);
    // key in invalid username
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("seand")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("12")
    await driver.findElement(By.name("rememberMeLogin")).click()
    await driver.findElement(By.id(":r2:")).click()

    // failure toast should be shown
    const toast = await driver.wait(until.elementLocated(By.css(".login-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Login failure!\nInvalid username or password');
  })
})
