// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.sleep(2000);
  await driver.findElement(By.name("username")).click()
  await driver.findElement(By.name("username")).sendKeys("seand")
  await driver.findElement(By.name("password")).click()
  await driver.findElement(By.name("password")).sendKeys("123")
  await driver.findElement(By.name("rememberMeLogin")).click()
  await driver.findElement(By.id(":r2:")).click()
}

async function navigateToAddProduct(driver) {
  await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6) > .MuiListItemText-root")).click()
}

const firstUPC = "000000000001"

describe('Add Product', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await navigateToLogin(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    await navigateToAddProduct(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/add-product'), 5000);
  })
  afterEach(async function () {
    await driver.quit();
  })

  it('adds product with new product name and valid UPC', async function () {
    const productName = "Test Product"

    await driver.wait(until.elementLocated(By.name("product-name")), 10000);

    await driver.findElement(By.name("product-name")).click()
    await driver.findElement(By.name("product-name")).sendKeys(productName)

    await driver.findElement(By.name("product-upc")).click()
    await driver.findElement(By.name("product-upc")).sendKeys(firstUPC)  // MUST CHNAGE ON EVERY TEST RUN

    await driver.findElement(By.id('product-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".product-add-success-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Product added successfully');
  })

  it('does not add product with no product name', async function () {
    const localUPC = "000000000002"

    await driver.wait(until.elementLocated(By.name("product-name")), 10000);

    await driver.findElement(By.name("product-upc")).click()
    await driver.findElement(By.name("product-upc")).sendKeys(localUPC)

    await driver.findElement(By.id('product-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".product-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add product.');
  })

  it('does not add product with invalid UPC', async function () {
    const localName = "Test Product 1"

    await driver.wait(until.elementLocated(By.name("product-name")), 10000);

    await driver.findElement(By.name("product-name")).click()
    await driver.findElement(By.name("product-name")).sendKeys(localName)

    await driver.findElement(By.name("product-upc")).click()
    await driver.findElement(By.name("product-upc")).sendKeys("0000001")

    await driver.findElement(By.id('product-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".product-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add product.');
  })

  it('does not add product with UPC that already exists', async function () {
    const localName = "Test Product 2"

    await driver.wait(until.elementLocated(By.name("product-name")), 10000);

    await driver.findElement(By.name("product-name")).click()
    await driver.findElement(By.name("product-name")).sendKeys(localName)

    await driver.findElement(By.name("product-upc")).click()
    await driver.findElement(By.name("product-upc")).sendKeys(firstUPC)

    await driver.findElement(By.id('product-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".product-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add product.');
  })
})

// ADDED "Test Product" with UPC "000000000001"