// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.sleep(2000);
  await driver.findElement(By.name("username")).click()
  await driver.findElement(By.name("username")).sendKeys("seand")
  await driver.findElement(By.name("password")).click()
  await driver.findElement(By.name("password")).sendKeys("123")
  await driver.findElement(By.name("rememberMeLogin")).click()
  await driver.findElement(By.id(":r2:")).click()
}

async function navigateToAddSupplier(driver) {
  await driver.findElement(By.css(".MuiButtonBase-root:nth-child(5) > .MuiListItemText-root")).click()
}

const firstUEN = "000000001A"

describe('Add Supplier', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await navigateToLogin(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    await navigateToAddSupplier(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/add-supplier'), 5000);
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('adds supplier with supplier name, address and valid UEN', async function() {
    const supplierName = "Test Supplier"
    const supplierAddress = "Test Address"

    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()
    await driver.findElement(By.name("supplier-name")).sendKeys(supplierName)
    await driver.findElement(By.name("supplier-address")).click()
    await driver.findElement(By.name("supplier-address")).sendKeys(supplierAddress)
    await driver.findElement(By.name("supplier-uen")).click()
    await driver.findElement(By.name("supplier-uen")).sendKeys(firstUEN)  // MUST CHANGE ON EVERY TEST RUN

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-success-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Supplier added successfully');
  })

  it('does not add supplier with no supplier name', async function() {
    const supplierAddress = "Test Address 1"
    const supplierUEN = "000000001C"

    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()

    await driver.findElement(By.name("supplier-address")).sendKeys(supplierAddress)
    await driver.findElement(By.name("supplier-uen")).click()
    await driver.findElement(By.name("supplier-uen")).sendKeys(supplierUEN)

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add supplier.');
  })

  it('does not add supplier with no UEN', async function() {
    const supplierName = "Test Supplier 2"
    const supplierAddress = "Test Address 2"

    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()
    await driver.findElement(By.name("supplier-name")).sendKeys(supplierName)

    await driver.findElement(By.name("supplier-address")).click()
    await driver.findElement(By.name("supplier-address")).sendKeys(supplierAddress)

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add supplier.');
  })

  it('adds supplier with no address', async function() {
    const supplierName = "Test Supplier 3"
    const supplierUEN = "000000001B"
    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()
    await driver.findElement(By.name("supplier-name")).sendKeys(supplierName)

    await driver.findElement(By.name("supplier-uen")).click()
    await driver.findElement(By.name("supplier-uen")).sendKeys(supplierUEN)

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-success-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Supplier added successfully');
  })

  it('does not add supplier with existing supplier UEN', async function() {
    const supplierName = "Test Supplier 4"
    const supplierAddress = "Test Address 4"

    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()
    await driver.findElement(By.name("supplier-name")).sendKeys(supplierName)
    await driver.findElement(By.name("supplier-address")).click()
    await driver.findElement(By.name("supplier-address")).sendKeys(supplierAddress)
    await driver.findElement(By.name("supplier-uen")).click()
    await driver.findElement(By.name("supplier-uen")).sendKeys(firstUEN)

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add supplier.');
  })

  it('does not add supplier with invalid UEN', async function() {
    const supplierName = "Test Supplier 5"
    const supplierAddress = "Test Address 5"
    const supplierUEN = "00000A"

    await driver.wait(until.elementLocated(By.name("supplier-name")), 10000);
    await driver.findElement(By.name("supplier-name")).click()
    await driver.findElement(By.name("supplier-name")).sendKeys(supplierName)
    await driver.findElement(By.name("supplier-address")).click()
    await driver.findElement(By.name("supplier-address")).sendKeys(supplierAddress)
    await driver.findElement(By.name("supplier-uen")).click()
    await driver.findElement(By.name("supplier-uen")).sendKeys(supplierUEN)

    await driver.findElement(By.id('supplier-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".supplier-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add supplier.');
  })
})

// ADDED "Test Supplier" with UEN: "000000001A" AND "Test Supplier 3" with UEN: "000000001B"