// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');
const { fi } = require('date-fns/locale');

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.sleep(2000);
  await driver.findElement(By.name("username")).click()
  await driver.findElement(By.name("username")).sendKeys("seand")
  await driver.findElement(By.name("password")).click()
  await driver.findElement(By.name("password")).sendKeys("123")
  await driver.findElement(By.name("rememberMeLogin")).click()
  await driver.findElement(By.id(":r2:")).click()
}

async function navigateToAddPayment(driver) {
  await driver.findElement(By.css(".MuiButtonBase-root:nth-child(4) > .MuiListItemText-root")).click()
}

const firstReferenceNumber = "000000001A"

describe('Add Payment', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await navigateToLogin(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    await navigateToAddPayment(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/add-payment'), 5000);
  })
  afterEach(async function() {
    await driver.sleep(2000)
    await driver.quit();
  })
  it('adds payment with recipient name, new reference number, date of payment, existing payment type and valid amount', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const recipientName = "Test Recipient"
    const dateOfPayment = "01012021"
    const paymentType = "paynow"
    const amount = "100"

    await driver.findElement(By.name("payment-recipient-name")).click()
    await driver.findElement(By.name("payment-recipient-name")).sendKeys(recipientName)

    await driver.findElement(By.name("payment-reference-number")).click()
    await driver.findElement(By.name("payment-reference-number")).sendKeys(firstReferenceNumber)

    await driver.findElement(By.name("payment-date-of-payment")).click()
    await driver.findElement(By.name("payment-date-of-payment")).sendKeys(dateOfPayment)

    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()

    await driver.findElement(By.name("payment-amount")).click()
    await driver.findElement(By.name("payment-amount")).sendKeys(amount)

    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-success-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Payment added successfully');
  })

  it('does not add payment with no recipient name', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const referenceNumber = "100000000A"
    const dateOfPayment = "01012021"
    const paymentType = "paynow"
    const amount = "100"

    await driver.findElement(By.name("payment-reference-number")).click()
    await driver.findElement(By.name("payment-reference-number")).sendKeys(referenceNumber)

    await driver.findElement(By.name("payment-date-of-payment")).click()
    await driver.findElement(By.name("payment-date-of-payment")).sendKeys(dateOfPayment)

    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()

    await driver.findElement(By.name("payment-amount")).click()
    await driver.findElement(By.name("payment-amount")).sendKeys(amount)

    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add payment.');
  })

  it('does not add payment with no reference number', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const recipientName = "Test Recipient 1"

    const dateOfPayment = "01012021"
    const paymentType = "paynow"
    const amount = "100"

    await driver.findElement(By.name("payment-recipient-name")).click()
    await driver.findElement(By.name("payment-recipient-name")).sendKeys(recipientName)

    await driver.findElement(By.name("payment-date-of-payment")).click()
    await driver.findElement(By.name("payment-date-of-payment")).sendKeys(dateOfPayment)

    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()

    await driver.findElement(By.name("payment-amount")).click()
    await driver.findElement(By.name("payment-amount")).sendKeys(amount)

    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add payment.');
  })

  it('does not add payment with no date of payment', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const recipientName = "Test Recipient 2"
    const referenceNumber = "100000000A"

    const paymentType = "paynow"
    const amount = "100"

    await driver.findElement(By.name("payment-recipient-name")).click()
    await driver.findElement(By.name("payment-recipient-name")).sendKeys(recipientName)

    await driver.findElement(By.name("payment-reference-number")).click()
    await driver.findElement(By.name("payment-reference-number")).sendKeys(referenceNumber)


    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()

    await driver.findElement(By.name("payment-amount")).click()
    await driver.findElement(By.name("payment-amount")).sendKeys(amount)

    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add payment.');
  })

  it('does not add payment with no amount', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const recipientName = "Test Recipient 3"
    const referenceNumber = "000000000C"
    const dateOfPayment = "01012021"
    const paymentType = "paynow"

    await driver.findElement(By.name("payment-recipient-name")).click()
    await driver.findElement(By.name("payment-recipient-name")).sendKeys(recipientName)

    await driver.findElement(By.name("payment-reference-number")).click()
    await driver.findElement(By.name("payment-reference-number")).sendKeys(referenceNumber)

    await driver.findElement(By.name("payment-date-of-payment")).click()
    await driver.findElement(By.name("payment-date-of-payment")).sendKeys(dateOfPayment)

    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()


    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add payment.');
  })

  it('does not add payment with existing reference number', async function() {
    await driver.wait(until.elementLocated(By.name("payment-recipient-name")), 10000);

    const recipientName = "Test Recipient 5"
    const dateOfPayment = "01012021"
    const paymentType = "paynow"
    const amount = "100"

    await driver.findElement(By.name("payment-recipient-name")).click()
    await driver.findElement(By.name("payment-recipient-name")).sendKeys(recipientName)

    await driver.findElement(By.name("payment-reference-number")).click()
    await driver.findElement(By.name("payment-reference-number")).sendKeys(firstReferenceNumber)

    await driver.findElement(By.name("payment-date-of-payment")).click()
    await driver.findElement(By.name("payment-date-of-payment")).sendKeys(dateOfPayment)

    await driver.findElement(By.css(".payment-type-autocomplete")).click()
    await driver.findElement(By.name("payment-type-input")).sendKeys(paymentType)
    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    const suggestedElement = await driver.findElement(By.xpath("//li[contains(text(), paymentType)]"))
    await suggestedElement.click()

    await driver.findElement(By.name("payment-amount")).click()
    await driver.findElement(By.name("payment-amount")).sendKeys(amount)

    await driver.findElement(By.id('payment-submit-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".payment-add-failure-toast")), 10000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Failed to add payment.');
  })

})

// ADDED "Test Recipient" with ref no.: "000000001A"