// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.sleep(2000);
  await driver.findElement(By.name("username")).click()
  await driver.findElement(By.name("username")).sendKeys("seand")
  await driver.findElement(By.name("password")).click()
  await driver.findElement(By.name("password")).sendKeys("123")
  await driver.findElement(By.name("rememberMeLogin")).click()
  await driver.findElement(By.id(":r2:")).click()
}

async function clickInvoiceFilterButton(driver) {
  await driver.wait(until.elementLocated(By.id('invoice-filter-button')), 30000);
  await driver.findElement(By.id('invoice-filter-button')).click()
}
async function clickSOAFilterButton(driver) {
  await driver.wait(until.elementLocated(By.id('soa-filter-button')), 30000);
  await driver.findElement(By.id('soa-filter-button')).click()
}

const firstRowIDColInvoice = ".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(1) > .MuiDataGrid-cellContent"
const firstRowSupplierColInvoice = ".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(2) > .MuiDataGrid-cellContent"
const firstRowPriceColInvoice = ".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(3) > .MuiDataGrid-cellContent"
const firstRowPaidColInvoice = ".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(4) > .MuiDataGrid-cellContent"

const firstRowIDColSOA = ".soa-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(1) > .MuiDataGrid-cellContent"
const firstRowSupplierColSOA = ".soa-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(2) > .MuiDataGrid-cellContent"
const firstRowOutstandingColSOA = ".soa-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(3) > .MuiDataGrid-cellContent"
const firstRowPaidColSOA = ".soa-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(4) > .MuiDataGrid-cellContent"


describe('Dashboard', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await navigateToLogin(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('shows table of invoices', async function() {
    await driver.wait(until.elementLocated(By.css(".invoice-card")), 30000);
    assert.ok(await driver.findElement(By.css(".invoice-card")).isDisplayed());
    assert.ok(await driver.findElement(By.css(".invoice-table")).isDisplayed());
  })

  it('filters invoices based on Invoice ID', async function() {
    const sampleInvoiceID = await driver.findElement(By.css(firstRowIDColInvoice)).getText()
    await clickInvoiceFilterButton(driver);

    await driver.wait(until.elementLocated(By.name("invoiceIDSearch")), 30000);
    await driver.findElement(By.name("invoiceIDSearch")).click()
    await driver.findElement(By.name("invoiceIDSearch")).sendKeys(sampleInvoiceID)
    await driver.findElement(By.id("invoice-search-button")).click()

    await driver.sleep(1000)

    await driver.wait(until.elementLocated(By.css(firstRowIDColInvoice)), 30000);
    const element = await driver.findElement(By.css(firstRowIDColInvoice))
    await driver.wait(async () => (await element.getText()).trim() !== '', 5000);
    const elementText = await element.getText()
    assert.ok(elementText.includes(sampleInvoiceID));
  })

  it('filters invoices based on Supplier', async function() {
    await clickInvoiceFilterButton(driver);

    const searchValue = "test"
    await driver.wait(until.elementLocated(By.css(".supplier-autocomplete")), 30000);
    await driver.findElement(By.css(".supplier-autocomplete")).click()
    await driver.findElement(By.name("supplier-input")).sendKeys(searchValue)

    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    await driver.sleep(1000)
    const suggestedElement = await driver.findElement(By.xpath(`//li[contains(text(), ${searchValue})]`))
    const suggestedElementText = await suggestedElement.getText()
    await suggestedElement.click()

    await driver.findElement(By.id("invoice-search-button")).click()
    await driver.sleep(1000)

    await driver.wait(until.elementLocated(By.css(firstRowSupplierColInvoice)), 30000);
    const element = await driver.findElement(By.css(firstRowSupplierColInvoice))
    await driver.wait(async () => (await element.getText()).trim() !== '', 5000);
    const elementText = await element.getText()
    assert.equal(elementText, suggestedElementText)
  })

  it('filters invoices based on Total Price After GST', async function() {
    const samplePrice = await driver.findElement(By.css(firstRowPriceColInvoice)).getText()
    console.log(samplePrice)
    const min = parseFloat(samplePrice) - 100
    const max = parseFloat(samplePrice) + 100

    await clickInvoiceFilterButton(driver);
    await driver.wait(until.elementLocated(By.name("minTotalPriceAfterGSTSearch")), 30000);

    await driver.findElement(By.name("minTotalPriceAfterGSTSearch")).click()
    await driver.findElement(By.name("minTotalPriceAfterGSTSearch")).sendKeys(min.toString())
    await driver.findElement(By.name("maxTotalPriceAfterGSTSearch")).click()
    await driver.findElement(By.name("maxTotalPriceAfterGSTSearch")).sendKeys(max.toString())
    await driver.findElement(By.id("invoice-search-button")).click()

    await driver.sleep(1000);
    await driver.executeScript('window.scrollBy(0, 75);')
    await driver.wait(until.elementLocated(By.css(firstRowPriceColInvoice)), 30000);
    const element = await driver.findElement(By.css(firstRowPriceColInvoice))
    const elementText = await element.getText()
    const elementNumber = parseFloat(elementText)

    assert.ok(elementNumber >= min && elementNumber <= max)
  })

  it('shows table of statement of accounts', async function() {
    await driver.wait(until.elementLocated(By.css(".soa-card")), 30000);
    assert.ok(await driver.findElement(By.css(".soa-card")).isDisplayed());
    assert.ok(await driver.findElement(By.css(".soa-table")).isDisplayed());
  })

  it('filters statement of accounts based on Statement of Account ID', async function() {
    const sampleSOAID = await driver.findElement(By.css(firstRowIDColSOA)).getText()
    await clickSOAFilterButton(driver);

    await driver.wait(until.elementLocated(By.name("referenceNumberSearch")), 30000);
    await driver.findElement(By.name("referenceNumberSearch")).click()
    await driver.findElement(By.name("referenceNumberSearch")).sendKeys(sampleSOAID)
    await driver.findElement(By.id("soa-search-button")).click()

    await driver.sleep(1000)
    await driver.wait(until.elementLocated(By.css(firstRowIDColSOA)), 10000);
    const element = await driver.findElement(By.css(firstRowIDColSOA))
    const elementText = await element.getText()
    assert.ok(elementText.includes(sampleSOAID));
  })

  it('filters statement of accounts based on Supplier', async function() {
    await clickSOAFilterButton(driver);

    const searchValue = "a"
    await driver.wait(until.elementLocated(By.css(".supplier-autocomplete")), 30000);
    await driver.findElement(By.css(".supplier-autocomplete")).click()
    await driver.findElement(By.name("supplier-input")).sendKeys(searchValue)

    await driver.wait(until.elementLocated(By.css('.MuiAutocomplete-popper')), 5000)
    await driver.sleep(1000)
    const suggestedElement = await driver.findElement(By.xpath(`//li[contains(text(), ${searchValue})]`))
    const suggestedElementText = await suggestedElement.getText()
    await suggestedElement.click()

    await driver.findElement(By.id("soa-search-button")).click()
    await driver.sleep(1000)

    await driver.wait(until.elementLocated(By.css(firstRowSupplierColSOA)), 30000);
    const element = await driver.findElement(By.css(firstRowSupplierColSOA))
    const elementText = await element.getText()
    assert.equal(elementText, suggestedElementText)
  })

  it('filters statement of accounts based on Amount Outstanding', async function() {
    const sampleOutstanding = await driver.findElement(By.css(firstRowOutstandingColSOA)).getText()
    const min = parseFloat(sampleOutstanding) - 100
    const max = parseFloat(sampleOutstanding) + 100

    await clickSOAFilterButton(driver);
    await driver.wait(until.elementLocated(By.name("minAmountOutstandingSearch")), 30000);

    await driver.findElement(By.name("minAmountOutstandingSearch")).click()
    await driver.findElement(By.name("minAmountOutstandingSearch")).sendKeys(min.toString())
    await driver.findElement(By.name("maxAmountOutstandingSearch")).click()
    await driver.findElement(By.name("maxAmountOutstandingSearch")).sendKeys(max.toString())
    await driver.findElement(By.id("soa-search-button")).click()

    await driver.sleep(1000);
    await driver.wait(until.elementLocated(By.css(firstRowOutstandingColSOA)), 30000);
    const element = await driver.findElement(By.css(firstRowOutstandingColSOA))
    const elementText = await element.getText()
    const elementNumber = parseFloat(elementText)

    assert.ok(elementNumber >= min && elementNumber <= max)
  })

})
