// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');

async function navigateToLogin(driver) {
  await driver.get("http://localhost:3000/login")
  await driver.manage().window().setRect({ width: 1382, height: 744 })
  await driver.sleep(2000);
  await driver.findElement(By.name("username")).click()
  await driver.findElement(By.name("username")).sendKeys("seand")
  await driver.findElement(By.name("password")).click()
  await driver.findElement(By.name("password")).sendKeys("123")
  await driver.findElement(By.name("rememberMeLogin")).click()
  await driver.findElement(By.id(":r2:")).click()
}

async function sortPaid(driver) {
    await driver.wait(until.elementLocated(By.css(".invoice-table:nth-child(1) .MuiDataGrid-columnHeader:nth-child(4) .MuiDataGrid-columnHeaderTitleContainer:nth-child(1) .MuiButtonBase-root:nth-child(1)")), 10000)
    await driver.findElement(By.css('[data-field="paid"]')).click()
}

async function clickFirstInvoice(driver) {
    await driver.wait(until.elementLocated(By.css(".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(2) > .MuiDataGrid-cellContent")), 10000)
    await driver.findElement(By.css(".invoice-table .MuiDataGrid-row:nth-child(1) > .MuiDataGrid-cell:nth-child(2) > .MuiDataGrid-cellContent")).click()
}

async function clickInvoiceFilterButton(driver) {
  await driver.wait(until.elementLocated(By.id('invoice-filter-button')), 30000);
  await driver.findElement(By.id('invoice-filter-button')).click()
}

async function findTestInvoice(driver) {
  const testInvoice = "0000001"
  await driver.wait(until.elementLocated(By.name("invoiceIDSearch")), 30000);
  await driver.findElement(By.name("invoiceIDSearch")).click()
  await driver.findElement(By.name("invoiceIDSearch")).sendKeys(testInvoice)
  await driver.findElement(By.id("invoice-search-button")).click()

  await driver.sleep(2000)
  await clickFirstInvoice(driver)
}

describe('Individual Invoice', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
    await navigateToLogin(driver)
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    await driver.wait(until.elementLocated(By.css('.invoice-card')), 10000);
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('exports to csv', async function() {
    await clickInvoiceFilterButton(driver)
    await findTestInvoice(driver)

    await driver.wait(until.elementLocated(By.id('export-button')), 10000)
    await driver.findElement(By.id('export-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".export-invoice-success-toast")), 10000)
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Invoice exported successfully! Look at your Downloads.');

  })

  it('updates paid status', async function() {
    await sortPaid(driver);
    await driver.sleep(5000)
    await clickFirstInvoice(driver)

    await driver.executeScript('window.scrollBy(0, 100);')
    await driver.wait(until.elementLocated(By.id('paid-checkbox')), 10000)
    await driver.findElement(By.id('paid-checkbox')).click()

    await driver.executeScript('window.scrollTo(0, 0);')
    await driver.wait(until.elementLocated(By.id('update-button')), 10000)
    await driver.findElement(By.id('update-button')).click()

    await driver.sleep(1500)

    const alert = await driver.switchTo().alert();
    const alertText = await alert.getText()
    const expectedAlert = "Are you sure you want to update invoice"
    assert.ok(alertText.includes(expectedAlert))
    await alert.accept()

    await driver.switchTo().defaultContent()
    const toast = await driver.wait(until.elementLocated(By.css(".paid-invoice-success-toast")), 10000)
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Invoice updated successfully!');

    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    assert.strictEqual(await driver.getCurrentUrl(), 'http://localhost:3000/dashboard/app');

  })

  it('deletes invoice', async function() {
    await clickInvoiceFilterButton(driver)
    await findTestInvoice(driver)

    await driver.wait(until.elementLocated(By.id('delete-button')), 10000)
    await driver.findElement(By.id('delete-button')).click()

    const toast = await driver.wait(until.elementLocated(By.css(".delete-invoice-success-toast")), 10000)
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Invoice deleted successfully!');

    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 5000);
    assert.strictEqual(await driver.getCurrentUrl(), 'http://localhost:3000/dashboard/app');
  })
})
