// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');

async function login(driver, username, password) {
    await driver.get("http://localhost:3000/login")
    await driver.manage().window().setRect({ width: 1382, height: 744 })
    await driver.sleep(2000);
    // key in staff username
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys(username)
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys(password)
    await driver.findElement(By.name("rememberMeLogin")).click()
    await driver.findElement(By.id(":r2:")).click()

    // should redirect to dashboard
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/app'), 10000);
    assert.strictEqual(await driver.getCurrentUrl(), 'http://localhost:3000/dashboard/app');
}

async function staffLogin(driver) {
    await login(driver, "sean", "123")
}

async function managerLogin(driver) {
    await login(driver, "sean43", "123")
}

async function adminLogin(driver) {
    await login(driver, "seand", "123")
}

async function navigateToUserPage(driver) {
    await driver.wait(until.elementLocated(By.css(".MuiButtonBase-root:nth-child(7) > .MuiListItemText-root")), 30000);
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(7) > .MuiListItemText-root")).click()
    await driver.wait(until.urlIs('http://localhost:3000/dashboard/user'), 10000);
}


describe('User Permissions', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('staff cannot see other users in User page', async function() {
    await staffLogin(driver);
    await navigateToUserPage(driver);

    const toast = await driver.wait(until.elementLocated(By.css(".view-user-failure-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Your role level is too low to view page!\nUsers are hidden from your view!');
  })
  it('staff cannot add new user', async function() {
    await staffLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".view-user-failure-toast")), 30000);
    try {
        await driver.findElement(By.id("add-new-user-button")).click()
    } catch (e) {
        assert.ok(e);
    }
  })
  it('branch manager cannot see other users in User page', async function() {
    await managerLogin(driver);
    await navigateToUserPage(driver);

    const toast = await driver.wait(until.elementLocated(By.css(".view-user-failure-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Your role level is too low to view page!\nUsers are hidden from your view!');
  })
  it('branch manager can add new staff user', async function() {
    await managerLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".view-user-failure-toast")), 30000);
    await driver.findElement(By.id("add-new-user-button")).click()
    await driver.wait(until.urlIs('http://localhost:3000/registration'), 10000);

    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Test Staff 1")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123")

    await driver.findElement(By.css(".roleLevel")).click()
    await driver.sleep(2000)
    const optionText = 'Staff'
    const optionElement = await driver.findElement(By.xpath(`//li[contains(text(), "${optionText}")]`));
    await optionElement.click();

    await driver.findElement(By.id("register-button")).click()

    const toast = await driver.wait(until.elementLocated(By.css(".register-success-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Creation of account was successful!');
  })
  it('administrator can see other users in User page', async function() {
    await adminLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".user-table")), 30000);
  })
  it('administrator can add new staff user', async function() {
    await adminLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".user-table")), 30000);
    await driver.findElement(By.id("add-new-user-button")).click()
    await driver.wait(until.urlIs('http://localhost:3000/registration'), 10000);

    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Test Staff 2")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123")

    await driver.findElement(By.css(".roleLevel")).click()
    await driver.sleep(2000)
    const optionText = 'Staff'
    const optionElement = await driver.findElement(By.xpath(`//li[contains(text(), "${optionText}")]`));
    await optionElement.click();

    await driver.findElement(By.id("register-button")).click()

    const toast = await driver.wait(until.elementLocated(By.css(".register-success-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Creation of account was successful!');
  })
  it('administrator delete other users', async function() {
    await adminLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".user-table")), 30000);
    const NextPageButtonElement = await driver.findElement(By.xpath('//button[@aria-label="Go to next page"]'));
    await NextPageButtonElement.click();

    await driver.wait(until.elementLocated(By.id('delete-user-button')), 30000);
    await driver.findElement(By.id('delete-user-button')).click();

    await driver.wait(until.elementLocated(By.id("delete-user-dialog")), 30000);
    await driver.findElement(By.id("confirm-delete-user-button")).click();

    const toast = await driver.wait(until.elementLocated(By.css(".delete-user-success-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'User deleted successfully!');
  })
  it('administrator can add new branch manager user', async function() {
    await adminLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".user-table")), 30000);
    await driver.findElement(By.id("add-new-user-button")).click()
    await driver.wait(until.urlIs('http://localhost:3000/registration'), 10000);

    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("Test Branch Manager 1")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123")

    await driver.findElement(By.css(".roleLevel")).click()
    await driver.sleep(2000)
    const optionText = 'Branch Manager'
    const optionElement = await driver.findElement(By.xpath(`//li[contains(text(), "${optionText}")]`));
    await optionElement.click();

    await driver.findElement(By.id("register-button")).click()

    const toast = await driver.wait(until.elementLocated(By.css(".register-success-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Creation of account was successful!');
  })
  it('administrator can change other users passwords', async function() {
    await adminLogin(driver);
    await navigateToUserPage(driver);

    await driver.wait(until.elementLocated(By.css(".user-table")), 30000);
    const NextPageButtonElement = await driver.findElement(By.xpath('//button[@aria-label="Go to next page"]'));
    await NextPageButtonElement.click();

    await driver.wait(until.elementLocated(By.id('edit-password-button')), 30000);
    await driver.findElement(By.id('edit-password-button')).click();

    await driver.findElement(By.name("newPassword")).click()
    await driver.findElement(By.name("newPassword")).sendKeys("123")

    await driver.findElement(By.id("save-password-button")).click();

    const toast = await driver.wait(until.elementLocated(By.css(".update-password-success-toast")), 30000);
    await driver.wait(async () => (await toast.getText()).trim() !== '', 5000);
    assert.strictEqual(await toast.getText(), 'Password updated successfully!');
  })
})
